### ISSUE TITLE
What database does this amazing program use please?

### ISSUE THREAD

**Issue by Logansfury** [Jugran/lyrics-in-terminal#45]
Hello,

This is an amazing program and I am very impressed with the range of lyrics it successfully retrieves. I have lyric display widgets using the data bases of makeitpersonal.co, AZLyrics, and irclib respectively, and your program finds lyrics that all 3 running side by side return "No lyrics found" for.

May I please ask what database this uses? It seems very robust and as I was able to install your program with a simple terminal command I assume no API is required?

Thank you :)

**Comment by Jugran** [comment]
As you speculated there is no API in use, I am just using web scraping on client itself. I am doing 3 source search, if lyrics is not found in a source, I search in next.

1. Google search embedded lyrics (usually gets most lyrics)
2. Azlyrics
3. Genius


Since I am doing a google search in first step, it finds most appropriate lyrics even if artist name is not spelled or formatted correctly. Also works for covers from different artists.

If google embedded lyrics is not found, I'm looking for other sources (azlyrics, genius) links in the same html, so the most similar lyrics search works in all sources.

**Comment by Logansfury** [comment]
That's fantastic, thank you so much for the response.

I have recently converted a few PC's into Mint Linux boxes and am working
on lyrics display widgets using the linux app Conky. I have 3 widgets atm,
using the databases of makeitpersonal.co, AZLyrics, and irclib.

Your app has been showing the lyrics of many many songs that none of my 3
widgets can get lyrics from. Evidently Google search is the key to getting
more returns. I already had a plan to make one widget out of the three that
searches all 3 databases in sequence if unable to find lyrics on the first
database.

I will get with ChatGPT and work up a 4th widget using google search.

Thank you again for the solution!

Sincerely,

Logan
